/**
 * GuardAI Platform API
 *
 * GuardAI is an adversarial security assessment Platform for AI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@navinfo.eu
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.navinfo.guardai.api.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param codebaseName 
 * @param enabled 
 * @param group 
 * @param id 
 * @param name 
 * @param paperLink 
 * @param parameters 
 * @param tasks 
 * @param type 
 */

data class AIFilter (

    @Json(name = "codebase_name")
    val codebaseName: kotlin.String? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "group")
    val group: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "paper_link")
    val paperLink: kotlin.String? = null,

    @Json(name = "parameters")
    val parameters: kotlin.String? = null,

    @Json(name = "tasks")
    val tasks: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "type")
    val type: kotlin.String? = null

)

