/**
 * GuardAI Platform API
 *
 * GuardAI is an adversarial security assessment Platform for AI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@navinfo.eu
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.navinfo.guardai.api.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param enabled 
 * @param parameters 
 * @param type 
 */

data class FilterRequest (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "parameters")
    val parameters: kotlin.String? = null,

    @Json(name = "type")
    val type: FilterRequest.Type? = null

) {

    /**
     * 
     *
     * Values: adversarialAttacks,domainAdaptations,metaAttacks,noises
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "adversarial_attacks") adversarialAttacks("adversarial_attacks"),
        @Json(name = "domain_adaptations") domainAdaptations("domain_adaptations"),
        @Json(name = "meta_attacks") metaAttacks("meta_attacks"),
        @Json(name = "noises") noises("noises");
    }
}

