/**
 * GuardAI Platform API
 *
 * GuardAI is an adversarial security assessment Platform for AI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@navinfo.eu
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.navinfo.guardai.api.models

import com.navinfo.guardai.api.models.Metric
import com.navinfo.guardai.api.models.ModelHead

import com.squareup.moshi.Json

/**
 * 
 *
 * @param head 
 * @param metrics 
 */

data class HeadSetting (

    @Json(name = "head")
    val head: ModelHead? = null,

    @Json(name = "metrics")
    val metrics: kotlin.collections.List<Metric>? = null

)

