/**
 * GuardAI Platform API
 *
 * GuardAI is an adversarial security assessment Platform for AI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@navinfo.eu
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.navinfo.guardai.api.models

import com.navinfo.guardai.api.models.WorkerHeartbeatEntry

import com.squareup.moshi.Json

/**
 * 
 *
 * @param busyCount 
 * @param consumerCount 
 * @param messageCount 
 * @param workers 
 */

data class QueueInfoResponse (

    @Json(name = "busyCount")
    val busyCount: kotlin.Int? = null,

    @Json(name = "consumerCount")
    val consumerCount: kotlin.Int? = null,

    @Json(name = "messageCount")
    val messageCount: kotlin.Int? = null,

    @Json(name = "workers")
    val workers: kotlin.collections.List<WorkerHeartbeatEntry>? = null

)

