/**
 * GuardAI Platform API
 *
 * GuardAI is an adversarial security assessment Platform for AI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@navinfo.eu
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.navinfo.guardai.api.models

import com.navinfo.guardai.api.models.CraftedTestSettings
import com.navinfo.guardai.api.models.DatasetSetting
import com.navinfo.guardai.api.models.DetectionTestSettings
import com.navinfo.guardai.api.models.Metric
import com.navinfo.guardai.api.models.PassFailCriteria

import com.squareup.moshi.Json

/**
 * 
 *
 * @param approximateRobustness 
 * @param arParams 
 * @param batchWiseHPO 
 * @param configured 
 * @param craftedSettings 
 * @param datasetSetting 
 * @param detectionTestSettings 
 * @param epsExploration 
 * @param epsExplorationParams 
 * @param hpoId 
 * @param hpoParams 
 * @param metrics 
 * @param optimalParameterization 
 * @param overlayImageOnSegMap 
 * @param passFailCriteria 
 * @param passPercentage 
 * @param storeCompositeImages 
 * @param storeIntermediateData 
 * @param testType 
 */

data class TestSettings (

    @Json(name = "approximateRobustness")
    val approximateRobustness: kotlin.Boolean? = null,

    @Json(name = "arParams")
    val arParams: kotlin.Any? = null,

    @Json(name = "batchWiseHPO")
    val batchWiseHPO: kotlin.Boolean? = null,

    @Json(name = "configured")
    val configured: kotlin.Boolean? = null,

    @Json(name = "craftedSettings")
    val craftedSettings: CraftedTestSettings? = null,

    @Json(name = "datasetSetting")
    val datasetSetting: DatasetSetting? = null,

    @Json(name = "detectionTestSettings")
    val detectionTestSettings: DetectionTestSettings? = null,

    @Json(name = "epsExploration")
    val epsExploration: kotlin.Boolean? = null,

    @Json(name = "epsExplorationParams")
    val epsExplorationParams: kotlin.Any? = null,

    @Json(name = "hpoId")
    val hpoId: kotlin.Int? = null,

    @Json(name = "hpoParams")
    val hpoParams: kotlin.Any? = null,

    @Json(name = "metrics")
    val metrics: kotlin.collections.Map<kotlin.String, kotlin.collections.List<Metric>>? = null,

    @Json(name = "optimalParameterization")
    val optimalParameterization: kotlin.Boolean? = null,

    @Json(name = "overlayImageOnSegMap")
    val overlayImageOnSegMap: kotlin.Boolean? = null,

    @Json(name = "passFailCriteria")
    val passFailCriteria: kotlin.collections.List<PassFailCriteria>? = null,

    @Json(name = "passPercentage")
    val passPercentage: kotlin.Float? = null,

    @Json(name = "storeCompositeImages")
    val storeCompositeImages: kotlin.Boolean? = null,

    @Json(name = "storeIntermediateData")
    val storeIntermediateData: kotlin.Boolean? = null,

    @Json(name = "testType")
    val testType: TestSettings.TestType? = null

) {

    /**
     * 
     *
     * Values: crafted,detection,robustness
     */
    enum class TestType(val value: kotlin.String) {
        @Json(name = "Crafted") crafted("Crafted"),
        @Json(name = "Detection") detection("Detection"),
        @Json(name = "Robustness") robustness("Robustness");
    }
}

