"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.web_hook_settings import WebHookSettings
globals()['WebHookSettings'] = WebHookSettings
from guardai_api.model.webhook_request import WebhookRequest


class TestWebhookRequest(unittest.TestCase):
    """WebhookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookRequest(self):
        """Test WebhookRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WebhookRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
