"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.organization_response import OrganizationResponse
from guardai_api.model.transform import Transform
globals()['OrganizationResponse'] = OrganizationResponse
globals()['Transform'] = Transform
from guardai_api.model.model_response import ModelResponse


class TestModelResponse(unittest.TestCase):
    """ModelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelResponse(self):
        """Test ModelResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
