"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.register_request import RegisterRequest


class TestRegisterRequest(unittest.TestCase):
    """RegisterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterRequest(self):
        """Test RegisterRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegisterRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
