"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import guardai_api
from api.defenses_api import DefensesApi  # noqa: E501


class TestDefensesApi(unittest.TestCase):
    """DefensesApi unit test stubs"""

    def setUp(self):
        self.api = DefensesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_defense(self):
        """Test case for get_defense

        Get a defense.  # noqa: E501
        """
        pass

    def test_update_defense(self):
        """Test case for update_defense

        Update defense.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
