"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import guardai_api
from api.project_api import ProjectApi  # noqa: E501


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_project(self):
        """Test case for add_project

        Add a project to an organization.  # noqa: E501
        """
        pass

    def test_copy_project(self):
        """Test case for copy_project

        Make a copy of the project available to (optionally) another organization.  # noqa: E501
        """
        pass

    def test_copy_project_model(self):
        """Test case for copy_project_model

        Make a copy of the project model available to the organization.  # noqa: E501
        """
        pass

    def test_delete_data(self):
        """Test case for delete_data

        Delete project model data.  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete a project.  # noqa: E501
        """
        pass

    def test_download_project_data(self):
        """Test case for download_project_data

        Download project data.  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get a project.  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        Get list of projects.  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update project .  # noqa: E501
        """
        pass

    def test_upload_project_data(self):
        """Test case for upload_project_data

        Upload project data.  # noqa: E501
        """
        pass

    def test_upload_project_file(self):
        """Test case for upload_project_file

        Upload a file to the project and return a reference.  # noqa: E501
        """
        pass

    def test_use_model(self):
        """Test case for use_model

        Use an existing model to configure the project.  # noqa: E501
        """
        pass

    def test_verify_project(self):
        """Test case for verify_project

        Start the model verification process.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
