"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import guardai_api
from api.organization_api import OrganizationApi  # noqa: E501


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_organization(self):
        """Test case for add_organization

        Add organization.  # noqa: E501
        """
        pass

    def test_copy_organization(self):
        """Test case for copy_organization

        Make a copy of the organization to another organization (requires admin permissions).  # noqa: E501
        """
        pass

    def test_delete_organization(self):
        """Test case for delete_organization

        Delete an organization.  # noqa: E501
        """
        pass

    def test_delete_organization_file(self):
        """Test case for delete_organization_file

        Delete organization file.  # noqa: E501
        """
        pass

    def test_download_organization_file(self):
        """Test case for download_organization_file

        Download organization file.  # noqa: E501
        """
        pass

    def test_get_asset_definitions(self):
        """Test case for get_asset_definitions

        Get the assets defined for this organization.  # noqa: E501
        """
        pass

    def test_get_defined_hpo(self):
        """Test case for get_defined_hpo

        Get the hyper-parameter optimization methods defined for this organization.  # noqa: E501
        """
        pass

    def test_get_defined_transforms(self):
        """Test case for get_defined_transforms

        Get the transforms defined for this organization.  # noqa: E501
        """
        pass

    def test_get_members(self):
        """Test case for get_members

        Get all members (admin access rights required).  # noqa: E501
        """
        pass

    def test_get_organization(self):
        """Test case for get_organization

        Get organization by id.  # noqa: E501
        """
        pass

    def test_get_organization_file_usage(self):
        """Test case for get_organization_file_usage

        Get organization file project usage.  # noqa: E501
        """
        pass

    def test_get_organizations(self):
        """Test case for get_organizations

        Get all organizations - (requires admin permissions).  # noqa: E501
        """
        pass

    def test_rename_organization_file(self):
        """Test case for rename_organization_file

        Rename organization file.  # noqa: E501
        """
        pass

    def test_update_org_stats(self):
        """Test case for update_org_stats

        Update storage and accounting information for this organization (admin rights).  # noqa: E501
        """
        pass

    def test_update_organization(self):
        """Test case for update_organization

        Update organization.  # noqa: E501
        """
        pass

    def test_upload_organization_file(self):
        """Test case for upload_organization_file

        Upload a file to the organization and return a reference.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
