"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.metric_definition import MetricDefinition


class TestMetricDefinition(unittest.TestCase):
    """MetricDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetricDefinition(self):
        """Test MetricDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetricDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
