"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.profile_settings import ProfileSettings
globals()['ProfileSettings'] = ProfileSettings
from guardai_api.model.test_profile_request import TestProfileRequest


class TestTestProfileRequest(unittest.TestCase):
    """TestProfileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestProfileRequest(self):
        """Test TestProfileRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestProfileRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
