"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.assets_response import AssetsResponse


class TestAssetsResponse(unittest.TestCase):
    """AssetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetsResponse(self):
        """Test AssetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
