"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import guardai_api
from api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a user.  # noqa: E501
        """
        pass

    def test_get_logged_in_user(self):
        """Test case for get_logged_in_user

        Get the currently logged-in user.  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get a user.  # noqa: E501
        """
        pass

    def test_get_user_logs(self):
        """Test case for get_user_logs

        Get user logs.  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Get all users (access rights required).  # noqa: E501
        """
        pass

    def test_send_feedback(self):
        """Test case for send_feedback

        Send user feedback.  # noqa: E501
        """
        pass

    def test_update_profile(self):
        """Test case for update_profile

        Update profile of currently authenticated user.  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update user by user id - (admin permission required)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
