"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import guardai_api
from api.test_profiles_api import TestProfilesApi  # noqa: E501


class TestTestProfilesApi(unittest.TestCase):
    """TestProfilesApi unit test stubs"""

    def setUp(self):
        self.api = TestProfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_profile(self):
        """Test case for add_profile

        Add a profile to an organization using the provided test id as a template.  # noqa: E501
        """
        pass

    def test_add_test_profile_defense(self):
        """Test case for add_test_profile_defense

        Add a defense to the profile  # noqa: E501
        """
        pass

    def test_add_test_profile_filter(self):
        """Test case for add_test_profile_filter

        Add a filter to the profile  # noqa: E501
        """
        pass

    def test_copy_profile(self):
        """Test case for copy_profile

        Make a copy of a profile. To copy to a different organization, extra permissions are required.  # noqa: E501
        """
        pass

    def test_create_test_profile(self):
        """Test case for create_test_profile

        Create a new test profile  # noqa: E501
        """
        pass

    def test_delete_profile(self):
        """Test case for delete_profile

        Delete a profile by ID.  # noqa: E501
        """
        pass

    def test_get_test_profile(self):
        """Test case for get_test_profile

        Get the test profile.  # noqa: E501
        """
        pass

    def test_get_test_profiles(self):
        """Test case for get_test_profiles

        Get the profiles available for this user.  # noqa: E501
        """
        pass

    def test_remove_test_profile_defense(self):
        """Test case for remove_test_profile_defense

        Remove defense from test profile.  # noqa: E501
        """
        pass

    def test_update_test_profile(self):
        """Test case for update_test_profile

        Update profile by ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
