"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.user_settings import UserSettings
globals()['UserSettings'] = UserSettings
from guardai_api.model.authorized_user_response import AuthorizedUserResponse


class TestAuthorizedUserResponse(unittest.TestCase):
    """AuthorizedUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthorizedUserResponse(self):
        """Test AuthorizedUserResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthorizedUserResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
