"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import guardai_api
from guardai_api.model.worker_heartbeat_entry import WorkerHeartbeatEntry
globals()['WorkerHeartbeatEntry'] = WorkerHeartbeatEntry
from guardai_api.model.queue_info_response import QueueInfoResponse


class TestQueueInfoResponse(unittest.TestCase):
    """QueueInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueueInfoResponse(self):
        """Test QueueInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueueInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
