"""
    GuardAI Platform API

    GuardAI is an adversarial security assessment Platform for AI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import unittest

import guardai_api
from api.versions_api import VersionsApi  # noqa: E501


class TestVersionsApi(unittest.TestCase):
    """VersionsApi unit test stubs"""

    def setUp(self):
        self.api = VersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_platform_version(self):
        """Test case for get_platform_version

        Get platform version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
