"""
    Adversarial Security Assessment Platform for AI

    Adversarial Security Assessment Platform for AI API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asap_client
from asap_client.model.defense_response import DefenseResponse
from asap_client.model.test_settings import TestSettings
globals()['DefenseResponse'] = DefenseResponse
globals()['TestSettings'] = TestSettings
from asap_client.model.test_response import TestResponse


class TestTestResponse(unittest.TestCase):
    """TestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestResponse(self):
        """Test TestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
