"""
    Adversarial Security Assessment Platform for AI

    Adversarial Security Assessment Platform for AI API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asap_client
from asap_client.model.filter_request import FilterRequest


class TestFilterRequest(unittest.TestCase):
    """FilterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterRequest(self):
        """Test FilterRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
