"""
    Adversarial Security Assessment Platform for AI

    Adversarial Security Assessment Platform for AI API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: info@navinfo.eu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asap_client
from asap_client.model.model_head import ModelHead


class TestModelHead(unittest.TestCase):
    """ModelHead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelHead(self):
        """Test ModelHead"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelHead()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
